# Generated by Django 5.2.2 on 2025-06-09 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_at', models.DateTimeField()),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], default='SMS', max_length=10)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=12)),
                ('time', models.DateTimeField(default=datetime.datetime(2025, 6, 9, 9, 51, 48, 250317, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
