# Generated by Django 5.2.2 on 2025-06-09 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 10, 0, 48, 388573, tzinfo=datetime.timezone.utc)),
        ),
    ]
