# Generated by Django 5.2.2 on 2025-06-09 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 10, 9, 11, 521249, tzinfo=datetime.timezone.utc)),
        ),
    ]
